### ISSUE TITLE
Space-Travelers-Hub

### ISSUE THREAD

**Issue by chelobotix** [chelobotix/Space-Travelers-Hub#25]
[https://github.com/chelobotix/Space-Travelers-Hub/projects/1](https://github.com/chelobotix/Space-Travelers-Hub/projects/1)
2 members: @chelobotix @francis3400

**Comment by franclobo** [comment]
Hi @chelobotix and @francis3400, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted an issue that doesn't have the correct link to the [project](https://github.com/chelobotix/Space-Travelers-Hub/projects/1), You have submitted a link to your repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by chelobotix** [comment]
This is the correct link to the [project](https://github.com/chelobotix/Space-Travelers-Hub/projects/1)
Thank you

**Comment by zieeco** [comment]
# status: APPROVED :green_circle: :100: 

Hi, @franclobo, @chelobotix ,


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡
 
✅ Descriptive Issue 👍 
✅ Nice project setup 🔥 


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
